import subprocess
from pathlib import Path

from goof_troop_usa import memory_map
from toolchain.build_environment import (
    BUILD_DIRECTORY,
    GENERATED_MEMORY_MAP_INCLUDE_FILE,
    MAIN_SOURCE_FILE,
    assembler_executable,
)

GENERATED_FILE_WARNING = (
    "; Generated by python/toolchain/assembler.py -- do not edit.\n"
    "; The addresses are defined in python/goof_troop_usa/memory_map.py.\n\n")


def assembly_literal_of(value: int) -> str:
    return f"${value:0{2 if value <= 0xFF else 4 if value <= 0xFFFF else 6}X}"


def write_memory_map_include() -> None:
    addresses = {name: value for name, value in vars(memory_map).items()
                 if not name.startswith("_") and isinstance(value, int)}
    widest = max(len(name) for name in addresses)
    BUILD_DIRECTORY.mkdir(parents=True, exist_ok=True)
    GENERATED_MEMORY_MAP_INCLUDE_FILE.write_text(
        GENERATED_FILE_WARNING
        + "".join(f"!{name:<{widest}} = {assembly_literal_of(value)}\n"
                  for name, value in addresses.items()),
        encoding="utf-8")


def assemble_into(target_rom_file: Path, tools_directory: Path) -> None:
    if not assembler_executable(tools_directory).exists():
        raise SystemExit(f"the assembler is missing from {tools_directory} -- run "
                         f"python/download_build_tools.py {tools_directory} first")
    write_memory_map_include()
    completed = subprocess.run(
        [str(assembler_executable(tools_directory)), "--fix-checksum=on", f"-I{BUILD_DIRECTORY}",
         str(MAIN_SOURCE_FILE), str(target_rom_file)])
    if completed.returncode != 0:
        raise SystemExit("assembly failed")
